"""
utils/tools_data.py — Single source of truth for BUILTIN_TOOLS list.
Imported by both app.py (landing) and 0_Tools_Library.py (dashboard).
No Streamlit calls here — pure data only.
"""

BUILTIN_TOOLS = [
    dict(
        id="interview_coach",
        name="Interview Coach Hive",
        user="For job applicants & professionals",
        desc="Simulates mock interviews with role-specific questions, evaluates answers, and provides structured feedback with improved suggestions.",
        cat="professional",
        cat_label="Professional",
        turn="multi",
        cover="cv-1",
        page="/Interview_Coach",
        icon_svg='<path d="M12 1a3 3 0 0 0-3 3v8a3 3 0 0 0 6 0V4a3 3 0 0 0-3-3z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" y1="19" x2="12" y2="23"/><line x1="8" y1="23" x2="16" y2="23"/>',
    ),
    dict(
        id="doc_summarizer",
        name="Doc Summarizer Hive",
        user="For students & researchers",
        desc="Accepts pasted text and returns a structured summary, key points, and action items — designed for fast academic and professional use.",
        cat="academic",
        cat_label="Academic",
        turn="single",
        cover="cv-2",
        page="/Document_Summarizer",
        icon_svg='<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/>',
    ),
    dict(
        id="doc_paraphraser",
        name="Doc Paraphraser Hive",
        user="For students & writers",
        desc="Rewrites user-submitted text in formal, casual, academic, or simplified tone while fully preserving original meaning.",
        cat="academic",
        cat_label="Academic",
        turn="single",
        cover="cv-3",
        page="/Document_Paraphraser",
        icon_svg='<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/>',
    ),
    dict(
        id="gradewise",
        name="GradeWise Hive",
        user="For students",
        desc="Track subjects, enter itemized scores, calculate weighted grades, forecast passing risk, and review academic analytics.",
        cat="academic",
        cat_label="Academic",
        turn="multi",
        cover="cv-4",
        page="/Grade_Predictor",
        icon_svg='<line x1="18" y1="20" x2="18" y2="10"/><line x1="12" y1="20" x2="12" y2="4"/><line x1="6" y1="20" x2="6" y2="14"/>',
    ),
    dict(
        id="forecasting",
        name="Forecasting Hive",
        user="For students & planners",
        desc="Forecast required scores, test target-grade feasibility, identify academic risk, and generate a focused priority plan.",
        cat="academic",
        cat_label="Academic",
        turn="multi",
        cover="cv-6",
        page="/Forecasting",
        icon_svg='<path d="M3 3v18h18"/><path d="M7 15l4-4 3 3 5-7"/><circle cx="7" cy="15" r="1"/><circle cx="11" cy="11" r="1"/><circle cx="14" cy="14" r="1"/><circle cx="19" cy="7" r="1"/>',
    ),
    dict(
        id="roleplay_creator",
        name="Roleplay Creator Hive",
        user="For educators & trainers",
        desc="Configure an AI persona — historical figure, interviewer, or character — and engage in a structured in-character conversation.",
        cat="education",
        cat_label="Education",
        turn="multi",
        cover="cv-5",
        page="/Roleplay_Creator",
        icon_svg='<circle cx="12" cy="8" r="4"/><path d="M4 20c0-4 3.6-7 8-7s8 3 8 7"/>',
    ),
    dict(
        id="wellness_companion",
        name="Wellness Companion Hive",
        user="For general users",
        desc="A judgment-free space for emotional reflection and journaling. Not a clinical tool — a supportive companion for everyday wellbeing.",
        cat="wellness",
        cat_label="Wellness",
        turn="multi",
        cover="cv-6",
        page="/Wellness_Companion",
        icon_svg='<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>',
    ),
    dict(
        id="fact_checker",
        name="Fact Checker Hive",
        user="For general users",
        desc="Credibility analysis on news headlines, claims, or article excerpts — with logical consistency checks and verification source suggestions.",
        cat="media",
        cat_label="Media Literacy",
        turn="single",
        cover="cv-7",
        page="/Fact_Checker",
        icon_svg='<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>',
    ),
    dict(
        id="career_roadmap",
        name="Career Roadmap Hive",
        user="For professionals",
        desc="Structured career transition plan with identified skill gaps, learning milestones, and recommended resources based on your current role and goals.",
        cat="professional",
        cat_label="Professional",
        turn="single",
        cover="cv-8",
        page="/Career_Roadmap",
        icon_svg='<polygon points="3,11 22,2 13,21 11,13 3,11"/>',
    ),
    dict(
        id="grammar_checker",
        name="Grammar Checker Hive",
        user="For students & writers",
        desc="Review grammar, spelling, punctuation, and clarity. Get a writing quality score and targeted improvement suggestions without rewriting your voice.",
        cat="academic",
        cat_label="Academic",
        turn="single",
        cover="cv-2",
        page="/Grammar_Checker",
        icon_svg='<path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><polyline points="17,4 20,7 13,14 10,14 10,11"/>',
    ),
    dict(
        id="essay_generator",
        name="Essay Generator Hive",
        user="For students & content creators",
        desc="Generate a structured essay or article draft from a topic, tone, and essay type. Optionally paste reference notes for the AI to draw from.",
        cat="academic",
        cat_label="Academic",
        turn="single",
        cover="cv-3",
        page="/Essay_Generator",
        icon_svg='<path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/>',
    ),
    dict(
        id="quiz_flashcard_generator",
        name="Quiz & Flashcard Generator Hive",
        user="For students & educators",
        desc="Paste notes or a document excerpt and generate multiple choice questions, true/false quizzes, short answer sets, or study flashcards instantly.",
        cat="education",
        cat_label="Education",
        turn="single",
        cover="cv-4",
        page="/Quiz_Flashcard_Generator",
        icon_svg='<rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/><path d="M9 9h1m4 0h1M9 12h6"/>',
    ),
]
